version: 2

project_name: gotree

before:
    hooks:
        - go mod tidy

builds:
    - id: gotree
      main: ./cmd/gotree/
      binary: gotree
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
          - arm64
      ldflags:
          - -s
          - -w

archives:
    - id: all
      name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      formats: [tar.gz]
      format_overrides:
          - goos: windows
            formats: [zip]

checksum:
    name_template: "checksums.txt"

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"

release:
    draft: true
    prerelease: auto
    name_template: "{{ .ProjectName }} v{{ .Version }}"

universal_binaries:
    - replace: true
